version: "3"

services:
  workspace:
    image: localhost:5000/kkowa/terraform-module:local
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/var/workspace
